### ISSUE TITLE
Make use of nvm (Node.js version manager)?

### ISSUE THREAD

**Issue by tinogo** [unfoldedcircle/integration-node-library#38]
Hi,
I've just seen, that the Node.js integration library requires Node.js version v16.18, but leaves it quite open on how to obtain this quite outdated Node.js version.

From my point of view, it could make sense, to add nvm (Node.js version manager) to this repository (it is a file called `.nvmrc` with a single line of code in it (`v16.18`).

The installation and usage is quite straight forward:
1. Install nvm at first: https://github.com/nvm-sh/nvm
2. Checkout this repository
3. Execute `nvm install` or `nvm use` (the latter, if you already used the repo in the past)

This ensures, that every developer uses the same Node.js version, which should help prevent some bugs from using different Node.js versions. Updating to another Node.js also gets straight forward: Change the content of the `.nvmrc`-file to the new Node.js version, can `nvm install` and you are all done.

Furthermore it allows you to use the same Node.js version also in the Github-Actions (e.g. https://github.com/unfoldedcircle/integration-node-library/blob/main/.github/workflows/unit-tests.yml):

```
name: Run unit tests

on:
  push:
    paths:
      - '**/*.js'
      - '.github/**/*.yml'
      - 'package-lock.json'
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run configured tests
        run: npm run test
```

WDYT?

Should I submit a pull request for that?
